#!/usr/bin/env bash

# Do nothing if there is already a branch number in the commit message
if [[ $(head -n 1 $1) =~ '[0-9]+' ]]; then
  exit 0
fi

# Prepend a branch number if it can be determined from the branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
REGEX="([0-9]+)"
if [[ $BRANCH_NAME =~ $REGEX ]]; then
  BRANCH_NUM="${BASH_REMATCH[1]}"
  echo -e "[$BRANCH_NUM] $(cat $1)" > $1
else
  echo >&2 "Warning: Unable to determine branch number from branch name"
fi
