vim.opt.autoread = true
vim.opt.backup = false
vim.opt.clipboard = "unnamedplus"
vim.opt.expandtab = true
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.list = true
vim.opt.listchars = "nbsp:¬,tab:»·"
vim.opt.matchpairs = vim.opt.matchpairs + "<:>"
vim.opt.number = true
vim.opt.number = true
vim.opt.re = 0
vim.opt.relativenumber=true
vim.opt.ruler = true
vim.opt.scrolloff = 3
vim.opt.shiftwidth = 4
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.spell = false
vim.opt.spelloptions = "camel"
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.wrap = false
vim.opt.writebackup = false
